go:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.go"
          - "go.mod"
          - "go.sum"

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"

site:
  - changed-files:
      - any-glob-to-any-file:
          - "site/**"
          - "scripts/install.sh"

