run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - errcheck
    - errorlint
    - gocritic
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/joelklabo/ackchyually
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\\.go
      linters:
        - errcheck
        - bodyclose
