version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - errcheck
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - gosec
    - prealloc
    - nakedret
    - gocyclo
    - dogsled
    - goprintffuncname
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - tparallel
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - errcheck
        path: _test\\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/joelklabo/ackchyually
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

