name: Question
description: Ask a question about using or developing ackchyually
title: "q: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true

